### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by Yamakasi** [MetaSyntactical/google-directions-client#12]
Hi,

Why not add the instructions for the route, would be great!

Cheers,

**Comment by dweichert** [comment]
Hi Yamakasi,

perhaps the README.md can provide an answer? There is a description how to obtain an route object by passing coordinates to the RouteFactory and how to use the Google API client to gather more coordinates (waypoints), adding more detail to the route.

Can you provide a little more context so I can better understand what you are trying to achieve and where the documentation falls short?


Best regards,
David

**Comment by Yamakasi** [comment]
Hi David,

Thanks for you reply! If you get a route you also have the legs there which are the directions when you need to take a turn left or right between the waypoints.

Do that make it more clear for you ?

Cheers,

Matt

**Comment by dweichert** [comment]
Hi Matt,

the Google Directions API is called with at least two coordinates (lat,lng) and up to 23 waypoints. It returns a so-called polyline which can be decoded into coordinates again. The library takes care of the polyline decoding business and adds handling for routes with more than 23 waypoints (through repeated API-calls).

So you begin with something like:
50.1109756, 8.6824697 as your starting coordinates
50.1320079, 8.6829269 as your destination coordinates
and say 50.1128467, 8.7049644 as a waypoint you want to pass on the route.

When you pass this to the RouteFactory you get a Route object which can be passed to the client and you eventually end up with an array of coordinates which represent the route, e.g.:

array(119) {
  [0] =>
  class MetaSyntactical\GoogleDirections\Coordinate#58 (2) {
    private $latitude =>
    double(50.11102)
    private $longitude =>
    double(8.68244)
  }
  [1] =>
  class MetaSyntactical\GoogleDirections\Coordinate#56 (2) {
    private $latitude =>
    double(50.1112)
    private $longitude =>
    double(8.68294)
  }
  [2] =>
  class MetaSyntactical\GoogleDirections\Coordinate#59 (2) {
    private $latitude =>
    double(50.11136)
    private $longitude =>
    double(8.68364)
  }
...

The API will not tell you whether to turn right or left, instead if you put the resulting coordinates on a map and draw a line through them you get a route that is more detailed than the original few input coordinates.

If you want to give it a try I suggest looking at the [ClientLiveTest](https://github.com/MetaSyntactical/google-directions-client/blob/master/tests/ClientLiveTest.php). To run the test you need to run composer install (in order to install the dependencies inkl. PHPUnit). You may want to remove "codeclimate/php-test-reporter": "^0.2.0" from composer.json, as it gave me some trouble when I ran the tests a few minutes ago locally and is not required.


Hope this helps
David

**Comment by Yamakasi** [comment]
Hi,

Thanks for the explanation, but as you are using /directions you get back the steps from the API, or don't you agree about that ?

Thanks again!

Matt

**Comment by dweichert** [comment]
Hi,

yes I would agree. The coordinates you get back are the steps between the start and destination coordinates (and waypoints along the route if any were given).

The original use case why I wrote the library was that I had coordinates from vehicles and wanted to plot their route on a map. However I only had GPS coordinates for every few minutes so I needed more coordinates to fill these gaps in order to plot something which approximates the route the vehicles actually took rather than a few lines from one point to another.


David

**Comment by Yamakasi** [comment]
Hi,

Yes I understand, also usable in my case. 

Thanks a lot for this library tho :)

Cheers,

Matt
